name = "alf-portfolio-api"
main = "src/worker.ts"
compatibility_date = "2025-01-10"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "alf-portfolio-db"
database_id = "01e7645a-dc0f-4eba-83e5-2ccd116808ef"
preview_database_id = "01e7645a-dc0f-4eba-83e5-2ccd116808ef"

# R2 Bucket for images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "adele-lo-feudo-images"
preview_bucket_name = "adele-lo-feudo-images"
